apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-step-observer
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
