name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ko:
    name: Build Test with ko
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Get google/ko
        run: GO111MODULE=on go get github.com/google/ko/cmd/ko


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Build test for reconciler with ko
        run: ko publish ./cmd/controller -L

#      - name: Build test for e2e code
#        run: go build -tags e2e ./test/...

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Check out plumbing
        uses: actions/checkout@v2.3.4
        with:
          repository: tektoncd/plumbing
        env:
          GOPATH: /home/runner/work/

      - name: Check out code
        uses: actions/checkout@v2.3.4
        env:
          GOPATH: /home/runner/work/

      - name: Run presubmit-test.sh
        run: export PATH=$PATH:/home/runner/work/bin && go build ./...
