name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Get google/ko
        run: GO111MODULE=on go get github.com/google/ko/cmd/ko
        env:
          GOPATH: /home/runner/work/

      - name: Create KinD Cluster
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.9.0
          export PATH=$PATH:/home/runner/work/bin
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            image: kindest/node:v1.16.15@sha256:a89c771f7de234e6547d43695c7ab047809ffc71a0c3b65aa54eda051c45ed20
          EOF
        env:
          GOPATH: /home/runner/work/

      - uses: actions/checkout@v2.3.4

      - name: Run integration test
        run: |
          export PATH=$PATH:/home/runner/work/bin
          echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ github.repository_owner }} --password-stdin
          ./test/e2e-tests.sh
        env:
          KO_DOCKER_REPO: ${{ github.repository_owner }}
          GOPATH: /home/runner/work/
