name: Rerun Update Deps

on:
  repository_dispatch:
    types: [rerun-command]

jobs:
  update-deps:
    name: Rerun Auto Update Dependencies
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.client_payload.pull_request.labels.*.name, 'dependencies') && startsWith( github.event.client_payload.pull_request.title, '[scheduled]' ) }}
    steps:
      - name: Install hub cli
        uses: geertvdc/setup-hub@v1.0.0
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: get go-licenses
        run: go get github.com/google/go-licenses
        env:
          GOPATH: /home/runner/work/

      - name: Check out code into the Go module directory
        run: |
          git clone ${{ github.event.client_payload.github.payload.repository.clone_url }}
          cd ${{ github.event.client_payload.github.payload.repository.name }}
          git fetch origin pull/${{ github.event.client_payload.pull_request.number }}/head:update-deps

      - name: Run update sh
        run: |
          cd ${{ github.event.client_payload.github.payload.repository.name }}
          git config user.email "tom.24d.en@gmail.com"
          git config user.name "Tomoya Nishide bot"
          git checkout update-deps
          git rebase master
          export PATH=$PATH:/home/runner/work/bin
          ./hack/update-deps.sh --upgrade
          git add .
          git commit --amend --no-edit
        env:
          GOPATH: /home/runner/work/

      - name: force-push commit
        run: |
          cd ${{ github.event.client_payload.github.payload.repository.name }}
          hub push -f origin update-deps
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_BOT_TOKEN }}
